[package]
name = "crud-server"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = [ "runtime-tokio",  "sqlite", "macros" ] }
axum = { version = "0.8.8", features = ["macros", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
